# AI Generated Code by Deloitte + Cursor (BEGIN)
AWSTemplateFormatVersion: '2010-09-09'
Description: 'SDLC-AI Monitoring Infrastructure - CloudWatch Dashboard and Alarms'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  ProjectName:
    Type: String
    Default: sdlc-ai
  AlertEmail:
    Type: String
    Default: ''

Conditions:
  HasAlertEmail: !Not [!Equals [!Ref AlertEmail, '']]

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-alerts'

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasAlertEmail
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  MainDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-${Environment}-dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "ECS CPU Utilization",
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", "ServiceName", "${ProjectName}-${Environment}-backend-service", "ClusterName", "${ProjectName}-${Environment}-cluster"]
                ],
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "ALB Request Count",
                "metrics": [
                  ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", "${ProjectName}-${Environment}-alb"]
                ],
                "region": "${AWS::Region}"
              }
            }
          ]
        }

  ECSCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-ecs-cpu-high'
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Sub '${ProjectName}-${Environment}-backend-service'
        - Name: ClusterName
          Value: !Sub '${ProjectName}-${Environment}-cluster'
      AlarmActions:
        - !Ref AlertTopic

Outputs:
  AlertTopicArn:
    Value: !Ref AlertTopic
    Export:
      Name: !Sub '${ProjectName}-${Environment}-AlertTopicArn'
  DashboardUrl:
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-${Environment}-dashboard'
# AI Generated Code by Deloitte + Cursor (END)
